apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway-pv
  namespace: tyk
  labels:
    app: gateway-tyk
spec:
  storageClassName: local-storage
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/tyk-gateway"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: gateway-pvc
    namespace: tyk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-pvc
  namespace: tyk
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2G
  selector:
    matchLabels:
      app: gateway-tyk