apiVersion: v1
data:
  tyk.conf: |
    {
      "listen_address": "",
      "listen_port": 8081,
      "secret": "352d20ee67be67f6340b4c0605b044b7",
      "template_path": "/opt/tyk/templates",
      "tyk_js_path": "/opt/tyk/js/tyk.js",
      "middleware_path": "/opt/tyk/middleware",
      "use_db_app_configs": false,
      "db_app_conf_options": {
          "connection_string": "http://tyk-dashboard.tyk.svc.cluster.local:3000",
          "node_is_segmented": false,
          "tags": ["test2"]
      },
      "app_path": "/opt/tyk/apps/",
      "storage": {
        "type": "redis",
        "enable_cluster": true,
        "addrs": [
            "redis-cluster-0.redis-cluster.redis.svc.cluster.local:6379",
            "redis-cluster-3.redis-cluster.redis.svc.cluster.local:6379",
            "redis-cluster-1.redis-cluster.redis.svc.cluster.local:6379",
            "redis-cluster-4.redis-cluster.redis.svc.cluster.local:6379",
            "redis-cluster-2.redis-cluster.redis.svc.cluster.local:6379",       
            "redis-cluster-5.redis-cluster.redis.svc.cluster.local:6379"]
        ,
        "database": 0,
        "optimisation_max_idle": 2000,
        "optimisation_max_active": 4000,
        "username": "",
        "password": "",
        "use_ssl": false
      },
      "enable_analytics": false,
      "optimisations_use_async_session_write": true,
      "enable_non_transactional_rate_limiter": true,
      "enable_sentinel_rate_limiter": false,
      "enable_redis_rolling_limiter": false,
      "allow_master_keys": false,
      "hash_keys": true,
      "close_connections": true,
      "http_server_options": {
        "enable_websockets": true
      },
      "allow_insecure_configs": true,
      "coprocess_options": {
        "enable_coprocess": false,
        "coprocess_grpc_server": ""
      },
      "enable_bundle_downloader": true,
      "bundle_base_url": "",
      "global_session_lifetime": 100,
      "force_global_session_lifetime": false,
      "max_idle_connections_per_host": 100    
    }
kind: ConfigMap
metadata:
  name: tyk-gateway-conf