apiVersion: v1
kind: Service
metadata:
  name: tyk-gateway
  namespace: tyk
spec:
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 32500
    protocol: TCP
  selector:
    app: tyk-gateway
  type: NodePort
